okta:
  oauth2:
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    redirect-uri: /authorization-code/callback
#   postLogoutRedirectUri: http://localhost:8080/hello
